name = "TEMPO"
uuid = "9a001a95-9353-4c2c-8189-325f0668c279"
authors = ["Guo Chu <guochu604b@gmail.com>"]
version = "0.0.1"

[deps]
ImpurityModelBase = "a5817ebb-6d84-46c1-a17a-d25f868e249e"
QuAPI = "49288508-9298-4753-b2e7-d320e8956d6c"
