name = "TEMPO"
uuid = "9a001a95-9353-4c2c-8189-325f0668c279"
authors = ["Guo Chu <guochu604b@gmail.com>"]
version = "0.0.1"

[deps]
ImpurityModelBase = "a5817ebb-6d84-46c1-a17a-d25f868e249e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuAPI = "49288508-9298-4753-b2e7-d320e8956d6c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
